image: ubuntu:latest

before_script:
  - apt-get update --yes > /dev/null
  - DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ libavcodec-dev doxygen libboost-all-dev python3-opencv > /dev/null

stages:
  - build
  - documentation

build:
  stage: build
  script: echo "Building the app"
    - sh ./build.sh

# test:
#   stage: test
#   script: echo "Running tests"
# script:
# - sh ./tests.sh

#  - mv ./ <folderName> /html/ public

docum:
  stage: documentation
  - sh ./build.sh -DBUILD_DOCS=TRUE 
    - cd ./build
    - make docs
    - cd ..
    - mv ./docs/html/ public
  artifacts:
    paths:
    - public
  only:
    - master

